name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
        ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        ENVIRONMENT: ${{secrets.ENVIRONMENT}} # Set the active profile here
      run: |
        # Install AWS CLI
        sudo apt-get update && sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user
        export PATH=$PATH:$HOME/.local/bin
        # Package the application
        zip -r application.zip target/gabe-goshorn-web-be-0.0.1-SNAPSHOT.jar
        # Upload the package to S3
        aws s3 cp application.zip s3://$BUCKET_NAME/application.zip --region $AWS_REGION
        # Create a new application version
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$BUCKET_NAME,S3Key=application.zip
        # Update the environment to use the new application version
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
